export const mangaluruDestination = {
  id: 'mangaluru',
  name: 'Mangaluru',
  state: 'Karnataka',
  region: 'South India',
  category: 'Beaches',
  secondaryCategory: 'Food',
  image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1000&q=80',
  description: 'A coastal Karnataka port city known for its beaches, markets, historic architecture, and Tulu and Mangalorean food.',
  coordinates: { lat: 12.9141, lng: 74.8560 },
  bestTimeToVisit: 'October to February',
  approxBudgetPerDay: 2400,
  crowdLevel: 'Moderate',
  travelDifficulty: 'Easy',
  safetyRating: 4.5,
  safetyInfo: 'Use marked swimming areas at beaches, check local weather advisories, and use registered transport after dark.',
  isBeyondTheCrowd: false,
  popularActivities: ['Panambur Beach', 'St. Aloysius Chapel', 'Tannirbhavi Beach', 'Central Market food walk'],
  localSpecialty: 'Neer dosa, kori rotti, Mangalorean fish curry, chicken sukka, and Gadbad ice cream',
  tags: ['coastal', 'food', 'beaches', 'culture']
};

const mangaluruHotels = [
  { id: 'hotel-mangaluru-ocean-pearl', name: 'The Ocean Pearl', area: 'Hampankatta', destinationId: 'mangaluru', destinationName: 'Mangaluru', type: 'Hotel', image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=800&q=80', pricePerNight: 3500, rating: 4.5, reviewsCount: 1250, amenities: ['WiFi', 'AC', 'Breakfast', 'Parking'], distanceFromAttractions: 'Near central Mangaluru and major city attractions', cancellationPolicy: 'Free cancellation up to 24 hours before check-in', roomsAvailable: 4, availability: 'Demo availability · confirm with property', verified: false, description: 'Comfortable city stay near central Mangaluru with easy access to major attractions.' },
  { id: 'hotel-mangaluru-goldfinch', name: 'Goldfinch Hotel Mangaluru', area: 'Balmatta', destinationId: 'mangaluru', destinationName: 'Mangaluru', type: 'Hotel', image: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=800&q=80', pricePerNight: 4200, rating: 4.4, reviewsCount: 980, amenities: ['WiFi', 'AC', 'Restaurant', 'Parking'], distanceFromAttractions: 'Central location near Balmatta and Hampankatta', cancellationPolicy: 'Free cancellation up to 24 hours before check-in', roomsAvailable: 3, availability: 'Demo availability · confirm with property', verified: false, description: 'A convenient full-service hotel base for exploring Mangaluru markets, temples, and coastline.' },
  { id: 'hotel-mangaluru-vivanta', name: 'Vivanta Mangalore', area: 'Old Port Road', destinationId: 'mangaluru', destinationName: 'Mangaluru', type: 'Hotel', image: 'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=800&q=80', pricePerNight: 5600, rating: 4.6, reviewsCount: 870, amenities: ['WiFi', 'AC', 'Pool', 'Restaurant'], distanceFromAttractions: 'Near the old port and central waterfront', cancellationPolicy: 'Free cancellation up to 48 hours before check-in', roomsAvailable: 2, availability: 'Demo availability · confirm with property', verified: false, description: 'An upscale city stay close to the historic port district and central Mangaluru.' },
  { id: 'hotel-mangaluru-ginger', name: 'Ginger Mangalore', area: 'Kottara Chowki', destinationId: 'mangaluru', destinationName: 'Mangaluru', type: 'Business Hotel', image: 'https://images.unsplash.com/photo-1564501049412-61c2a3083791?auto=format&fit=crop&w=800&q=80', pricePerNight: 3200, rating: 4.2, reviewsCount: 760, amenities: ['WiFi', 'AC', 'Breakfast', 'Gym'], distanceFromAttractions: 'Kottara Chowki, with access to the city and highway', cancellationPolicy: 'Free cancellation up to 24 hours before check-in', roomsAvailable: 5, availability: 'Demo availability · confirm with property', verified: false, description: 'A practical modern stay for short city visits, with easy road connections around Mangaluru.' },
  { id: 'hotel-mangaluru-poonja', name: 'Hotel Poonja International', area: 'Hampankatta', destinationId: 'mangaluru', destinationName: 'Mangaluru', type: 'City Hotel', image: 'https://images.unsplash.com/photo-1590490360182-c33d57733427?auto=format&fit=crop&w=800&q=80', pricePerNight: 2400, rating: 4.0, reviewsCount: 650, amenities: ['WiFi', 'AC', 'Restaurant', 'Room Service'], distanceFromAttractions: 'In the central Hampankatta district', cancellationPolicy: 'Free cancellation up to 24 hours before check-in', roomsAvailable: 6, availability: 'Demo availability · confirm with property', verified: false, description: 'A central option close to shops, local eateries, and Mangaluru city transport.' },
  { id: 'hotel-mangaluru-summer-sands', name: 'Summer Sands Beach Resort', area: 'Ullal', destinationId: 'mangaluru', destinationName: 'Mangaluru', type: 'Beach Resort', image: 'https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?auto=format&fit=crop&w=800&q=80', pricePerNight: 4800, rating: 4.3, reviewsCount: 420, amenities: ['Beach Access', 'Pool', 'Restaurant', 'Parking'], distanceFromAttractions: 'Coastal location near Ullal beach', cancellationPolicy: 'Free cancellation up to 48 hours before check-in', roomsAvailable: 3, availability: 'Demo availability · confirm with property', verified: false, description: 'A relaxed coastal-style stay for travelers looking to spend time by the Arabian Sea.' },
  { id: 'hotel-mangaluru-pappilon', name: 'Hotel Pappilon', area: 'M.G. Road', destinationId: 'mangaluru', destinationName: 'Mangaluru', type: 'Hotel', image: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=800&q=80', pricePerNight: 2200, rating: 4.1, reviewsCount: 340, amenities: ['WiFi', 'AC', 'Breakfast', 'Laundry'], distanceFromAttractions: 'Near M.G. Road shopping and dining', cancellationPolicy: 'Free cancellation up to 24 hours before check-in', roomsAvailable: 4, availability: 'Demo availability · confirm with property', verified: false, description: 'A modest city stay with easy access to central shopping and neighborhood restaurants.' },
  { id: 'hotel-mangaluru-sai-arya', name: 'Sai Arya Residency', area: 'Kankanady', destinationId: 'mangaluru', destinationName: 'Mangaluru', type: 'Guesthouse', image: 'https://images.unsplash.com/photo-1510798831971-661eb04b3739?auto=format&fit=crop&w=800&q=80', pricePerNight: 1800, rating: 4.1, reviewsCount: 290, amenities: ['WiFi', 'AC', 'Parking', 'Family Rooms'], distanceFromAttractions: 'Kankanady, near local transit and neighborhood dining', cancellationPolicy: 'Free cancellation up to 24 hours before check-in', roomsAvailable: 3, availability: 'Demo availability · confirm with property', verified: false, description: 'A simple budget-friendly base for families and short stays in Mangaluru.' }
];

const mangaluruExperiences = [
  { id: 'exp-mangaluru-coastal-food', title: 'Mangaluru Coastal Food Walk', destinationId: 'mangaluru', category: 'Food', host: 'Coastal Kitchen Collective · Demo host', hostVerified: false, price: 850, duration: '3 Hours', languages: ['Kannada', 'Tulu', 'English'], rating: 4.8, reviewsCount: 84, image: 'https://images.unsplash.com/photo-1556910103-1c02745aae4d?auto=format&fit=crop&w=800&q=80', description: 'Sample neer dosa, goli baje, kori rotti, and seasonal coastal dishes at neighborhood eateries.', impactNote: 'Demo recommendation supporting independent neighborhood food businesses.', location: 'Hampankatta and Central Market', availableSlots: 6 },
  { id: 'exp-mangaluru-yakshagana', title: 'Yakshagana Stories & Costumes', destinationId: 'mangaluru', category: 'Culture', host: 'Coastal Arts Circle · Demo host', hostVerified: false, price: 700, duration: '2 Hours', languages: ['Kannada', 'Tulu', 'English'], rating: 4.9, reviewsCount: 61, image: 'https://images.unsplash.com/photo-1531058020387-3be344556be6?auto=format&fit=crop&w=800&q=80', description: 'Explore the music, expressive costumes, and storytelling tradition of coastal Karnataka.', impactNote: 'Demo cultural listing; check local schedules before visiting.', location: 'Mangaluru city', availableSlots: 8 },
  { id: 'exp-mangaluru-seafood-cooking', title: 'Mangalorean Seafood Cooking Session', destinationId: 'mangaluru', category: 'Food', host: 'Anitha’s Home Kitchen · Demo host', hostVerified: false, price: 1100, duration: '2.5 Hours', languages: ['Kannada', 'Tulu', 'English'], rating: 4.8, reviewsCount: 47, image: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&w=800&q=80', description: 'Learn the basics of a coastal fish curry and spice blend, with a vegetarian alternative on request.', impactNote: 'Demo home-cooking experience; dietary needs should be confirmed with the host.', location: 'Bejai', availableSlots: 4 },
  { id: 'exp-mangaluru-panambur-sunrise', title: 'Panambur Beach Sunrise Walk', destinationId: 'mangaluru', category: 'Nature', host: 'Coastline Walks · Demo host', hostVerified: false, price: 350, duration: '1.5 Hours', languages: ['Kannada', 'English', 'Hindi'], rating: 4.7, reviewsCount: 93, image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80', description: 'Start early with a guided shoreline walk and learn about coastal habitats and beach safety.', impactNote: 'Demo nature outing; follow beach access and safety advisories.', location: 'Panambur Beach', availableSlots: 10 },
  { id: 'exp-mangaluru-pilikula', title: 'Pilikula Nature & Culture Day', destinationId: 'mangaluru', category: 'Nature', host: 'Pilikula Day Guides · Demo host', hostVerified: false, price: 650, duration: '3 Hours', languages: ['Kannada', 'English'], rating: 4.6, reviewsCount: 52, image: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?auto=format&fit=crop&w=800&q=80', description: 'Explore green spaces and cultural attractions around the Pilikula area at an easy pace.', impactNote: 'Demo itinerary suggestion; check venue hours and entry details before travel.', location: 'Pilikula, Vamanjoor', availableSlots: 7 },
  { id: 'exp-mangaluru-handicraft', title: 'Coastal Craft & Weaving Workshop', destinationId: 'mangaluru', category: 'Handicrafts', host: 'Karavali Makers · Demo host', hostVerified: false, price: 550, duration: '2 Hours', languages: ['Kannada', 'Tulu', 'English'], rating: 4.7, reviewsCount: 38, image: 'https://images.unsplash.com/photo-1452860606245-08befc0ff44b?auto=format&fit=crop&w=800&q=80', description: 'Meet local makers and try a small hands-on craft inspired by coastal Karnataka materials.', impactNote: 'Demo workshop concept; materials and schedule vary by host.', location: 'Kadri', availableSlots: 5 },
  { id: 'exp-mangaluru-fishing-village', title: 'Fishing Harbor Morning Visit', destinationId: 'mangaluru', category: 'Fishing', host: 'Coastal Community Walks · Demo host', hostVerified: false, price: 500, duration: '2 Hours', languages: ['Kannada', 'Tulu', 'English'], rating: 4.6, reviewsCount: 44, image: 'https://images.unsplash.com/photo-1516937941344-00b4e0337589?auto=format&fit=crop&w=800&q=80', description: 'Learn about the daily rhythm of the coast from a respectful distance and see the harbor wake up.', impactNote: 'Demo listing; harbor access depends on local conditions and permission.', location: 'Bunder fishing harbor', availableSlots: 6 },
  { id: 'exp-mangaluru-tulu-stories', title: 'Tulu Stories & Old Town Walk', destinationId: 'mangaluru', category: 'Culture', host: 'Namma Ooru Storytellers · Demo host', hostVerified: false, price: 600, duration: '2 Hours', languages: ['Kannada', 'Tulu', 'English'], rating: 4.8, reviewsCount: 39, image: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=800&q=80', description: 'Walk through old-town lanes while hearing stories of local language, trade, and everyday life.', impactNote: 'Demo walking tour; route and access may change.', location: 'Bunder and Car Street', availableSlots: 8 }
];

const mangaluruGuides = [
  { id: 'guide-mangaluru-kavya', name: 'Kavya Rai', destinationId: 'mangaluru', destinationName: 'Mangaluru', photo: 'https://images.unsplash.com/photo-1551836022-d5d88e9218df?auto=format&fit=crop&w=400&q=80', languages: ['Kannada', 'Tulu', 'English'], expertise: ['Coastal heritage', 'Local history', 'Food walks'], dailyFee: 1400, experienceYears: 7, rating: 4.8, reviewsCount: 72, verifiedBadge: 'Demo profile · Verification not provided', verified: false, bio: 'A demo guide profile focused on Mangaluru’s neighborhoods, coastal traditions, and local food.', phone: 'Contact via TripEase demo' },
  { id: 'guide-mangaluru-rohan', name: 'Rohan Shetty', destinationId: 'mangaluru', destinationName: 'Mangaluru', photo: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=400&q=80', languages: ['Kannada', 'Hindi', 'English'], expertise: ['Beaches', 'Photography', 'Nature'], dailyFee: 1600, experienceYears: 6, rating: 4.7, reviewsCount: 58, verifiedBadge: 'Demo profile · Verification not provided', verified: false, bio: 'A demo profile for relaxed beach visits, coastal viewpoints, and photography outings.', phone: 'Contact via TripEase demo' },
  { id: 'guide-mangaluru-fathima', name: 'Fathima K', destinationId: 'mangaluru', destinationName: 'Mangaluru', photo: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=400&q=80', languages: ['Kannada', 'English', 'Hindi'], expertise: ['Food', 'Markets', 'Culture'], dailyFee: 1300, experienceYears: 5, rating: 4.9, reviewsCount: 64, verifiedBadge: 'Demo profile · Verification not provided', verified: false, bio: 'A demo guide profile for market visits and introductions to Mangalorean cuisine.', phone: 'Contact via TripEase demo' },
  { id: 'guide-mangaluru-arun', name: 'Arun D’Souza', destinationId: 'mangaluru', destinationName: 'Mangaluru', photo: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80', languages: ['Kannada', 'English', 'French'], expertise: ['Heritage', 'Architecture', 'Church history'], dailyFee: 1800, experienceYears: 9, rating: 4.8, reviewsCount: 81, verifiedBadge: 'Demo profile · Verification not provided', verified: false, bio: 'A demo profile for architecture, historic streets, and Mangaluru’s layered cultural history.', phone: 'Contact via TripEase demo' },
  { id: 'guide-mangaluru-meera', name: 'Meera Poojary', destinationId: 'mangaluru', destinationName: 'Mangaluru', photo: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=400&q=80', languages: ['Kannada', 'Tulu', 'Hindi'], expertise: ['Nature', 'Pilikula', 'Local history'], dailyFee: 1500, experienceYears: 8, rating: 4.7, reviewsCount: 49, verifiedBadge: 'Demo profile · Verification not provided', verified: false, bio: 'A demo profile for nature outings and family-friendly cultural stops around the city.', phone: 'Contact via TripEase demo' },
  { id: 'guide-mangaluru-naveen', name: 'Naveen Alva', destinationId: 'mangaluru', destinationName: 'Mangaluru', photo: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=400&q=80', languages: ['Kannada', 'Tulu', 'English', 'Hindi'], expertise: ['Fishing harbor', 'Coastal culture', 'Food'], dailyFee: 1700, experienceYears: 10, rating: 4.9, reviewsCount: 96, verifiedBadge: 'Demo profile · Verification not provided', verified: false, bio: 'A demo profile for learning about harbor life and coastal community traditions.', phone: 'Contact via TripEase demo' },
  { id: 'guide-mangaluru-sana', name: 'Sana D’Souza', destinationId: 'mangaluru', destinationName: 'Mangaluru', photo: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80', languages: ['English', 'Hindi', 'Kannada'], expertise: ['Food', 'Beaches', 'Photography'], dailyFee: 1450, experienceYears: 4, rating: 4.6, reviewsCount: 34, verifiedBadge: 'Demo profile · Verification not provided', verified: false, bio: 'A demo profile for first-time visitors interested in beaches, food, and photo stops.', phone: 'Contact via TripEase demo' }
];

const mangaluruFoods = [
  { id: 'food-mangaluru-neer-dosa', dishName: 'Neer dosa with coconut chutney', restaurantName: 'New Tajmahal Cafe', destination: 'Mangaluru', area: 'Hampankatta', cuisine: 'Mangalorean · South Indian', dietary: 'Pure Veg', iconicRestaurant: 'New Tajmahal Cafe · Demo recommendation', priceRange: '₹80–₹180', hygieneRating: 'Local listing · Demo recommendation', description: 'Soft rice crepes commonly served with coconut chutney and regional curries.', mustTryBadge: 'Local favorite', rating: 4.4, reviewsCount: 920, image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=800&q=80', openingHours: 'Breakfast and lunch; confirm current hours' },
  { id: 'food-mangaluru-buns', dishName: 'Mangalore buns', restaurantName: 'Ideal Cafe', destination: 'Mangaluru', area: 'Hampankatta', cuisine: 'Mangalorean · Cafe', dietary: 'Pure Veg', iconicRestaurant: 'Ideal Cafe · Demo recommendation', priceRange: '₹60–₹160', hygieneRating: 'Local listing · Demo recommendation', description: 'Lightly sweet, puffed banana puris often paired with coconut chutney.', mustTryBadge: 'Breakfast pick', rating: 4.5, reviewsCount: 810, image: 'https://images.unsplash.com/photo-1606491956689-2ea866880c84?auto=format&fit=crop&w=800&q=80', openingHours: 'Morning to evening; confirm current hours' },
  { id: 'food-mangaluru-goli-baje', dishName: 'Goli baje', restaurantName: 'Janatha Deluxe', destination: 'Mangaluru', area: 'Hampankatta', cuisine: 'Mangalorean · Snacks', dietary: 'Pure Veg', iconicRestaurant: 'Janatha Deluxe · Demo recommendation', priceRange: '₹70–₹180', hygieneRating: 'Local listing · Demo recommendation', description: 'Crisp outside and soft inside, these maida-and-yogurt fritters are a popular tea-time snack.', mustTryBadge: 'Tea-time snack', rating: 4.3, reviewsCount: 540, image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=800&q=80', openingHours: 'Lunch and dinner; confirm current hours' },
  { id: 'food-mangaluru-kori-rotti', dishName: 'Kori rotti', restaurantName: 'Shetty Lunch Home', destination: 'Mangaluru', area: 'Ballalbagh', cuisine: 'Mangalorean · Coastal', dietary: 'Non-Veg', iconicRestaurant: 'Shetty Lunch Home · Demo recommendation', priceRange: '₹240–₹480', hygieneRating: 'Local listing · Demo recommendation', description: 'A coastal chicken curry served with crisp rice wafers that soften in the gravy.', mustTryBadge: 'Coastal classic', rating: 4.4, reviewsCount: 770, image: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?auto=format&fit=crop&w=800&q=80', openingHours: 'Lunch and dinner; confirm current hours' },
  { id: 'food-mangaluru-fish-curry', dishName: 'Mangalorean fish curry meal', restaurantName: 'Giri Manja’s', destination: 'Mangaluru', area: 'Car Street', cuisine: 'Mangalorean · Seafood', dietary: 'Non-Veg', iconicRestaurant: 'Giri Manja’s · Demo recommendation', priceRange: '₹280–₹600', hygieneRating: 'Local listing · Demo recommendation', description: 'A rice meal with a tangy, spice-forward coastal fish curry; fish selection varies by catch.', mustTryBadge: 'Seafood pick', rating: 4.6, reviewsCount: 1030, image: 'https://images.unsplash.com/photo-1515003197210-e0cd7184f8b5?auto=format&fit=crop&w=800&q=80', openingHours: 'Lunch; confirm current hours' },
  { id: 'food-mangaluru-chicken-sukka', dishName: 'Chicken sukka and kori rotti', restaurantName: 'Machali', destination: 'Mangaluru', area: 'Kodialbail', cuisine: 'Mangalorean · Seafood and coastal', dietary: 'Non-Veg', iconicRestaurant: 'Machali · Demo recommendation', priceRange: '₹260–₹550', hygieneRating: 'Local listing · Demo recommendation', description: 'Dry-roasted coastal chicken with coconut and spices, often served with rice or rotti.', mustTryBadge: 'Spice favorite', rating: 4.5, reviewsCount: 880, image: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&w=800&q=80', openingHours: 'Lunch and dinner; confirm current hours' },
  { id: 'food-mangaluru-seafood', dishName: 'Fish thali and seasonal seafood', restaurantName: 'Hotel Narayana', destination: 'Mangaluru', area: 'Bunder', cuisine: 'Mangalorean · Seafood', dietary: 'Non-Veg', iconicRestaurant: 'Hotel Narayana · Demo recommendation', priceRange: '₹250–₹650', hygieneRating: 'Local listing · Demo recommendation', description: 'A simple coastal seafood meal with rice, curry, and a rotating selection of local fish.', mustTryBadge: 'Harbor-side meal', rating: 4.5, reviewsCount: 690, image: 'https://images.unsplash.com/photo-1535399831218-d5bd36d1a6b3?auto=format&fit=crop&w=800&q=80', openingHours: 'Lunch; confirm current hours' },
  { id: 'food-mangaluru-gadbad', dishName: 'Gadbad ice cream', restaurantName: 'Pabba’s', destination: 'Mangaluru', area: 'Lalbagh', cuisine: 'Dessert · Ice cream', dietary: 'Pure Veg', iconicRestaurant: 'Pabba’s · Demo recommendation', priceRange: '₹120–₹240', hygieneRating: 'Local listing · Demo recommendation', description: 'A layered ice-cream sundae with fruit, jelly, nuts, and assorted flavors.', mustTryBadge: 'City dessert', rating: 4.6, reviewsCount: 1120, image: 'https://images.unsplash.com/photo-1563805042-7684c019e1cb?auto=format&fit=crop&w=800&q=80', openingHours: 'Afternoon to late evening; confirm current hours' },
  { id: 'food-mangaluru-veg-meals', dishName: 'South Indian vegetarian meals', restaurantName: 'Hotel Sagar', destination: 'Mangaluru', area: 'Urwa', cuisine: 'South Indian · Vegetarian', dietary: 'Pure Veg', iconicRestaurant: 'Hotel Sagar · Demo recommendation', priceRange: '₹100–₹240', hygieneRating: 'Local listing · Demo recommendation', description: 'A homestyle vegetarian meal with rice, seasonal sides, and regional accompaniments.', mustTryBadge: 'Vegetarian meal', rating: 4.2, reviewsCount: 360, image: 'https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=800&q=80', openingHours: 'Breakfast and lunch; confirm current hours' },
  { id: 'food-mangaluru-breakfast', dishName: 'Neer dosa, buns, and local breakfast', restaurantName: 'Woodlands', destination: 'Mangaluru', area: 'Balmatta', cuisine: 'Mangalorean · South Indian', dietary: 'Pure Veg', iconicRestaurant: 'Woodlands · Demo recommendation', priceRange: '₹90–₹220', hygieneRating: 'Local listing · Demo recommendation', description: 'A vegetarian-friendly breakfast stop with regional dosa, idli, and seasonal specialties.', mustTryBadge: 'Breakfast table', rating: 4.3, reviewsCount: 410, image: 'https://images.unsplash.com/photo-1630383249896-424e482df921?auto=format&fit=crop&w=800&q=80', openingHours: 'Breakfast and lunch; confirm current hours' }
];

export const mangaluruListings = {
  hotels: mangaluruHotels,
  experiences: mangaluruExperiences,
  foods: mangaluruFoods,
  guides: mangaluruGuides
};

export const normalizeListingDestination = (value = '') => {
  const normalized = String(value).toLowerCase().replace(/[^a-z0-9]/g, '');
  return normalized === 'mangalore' || normalized === 'mangaluru' ? 'mangaluru' : normalized;
};

const fallbackProfiles = {
  goa: { area: 'Panaji and coastal Goa', type: 'coastal', specialty: 'Goan fish curry, poi, and bebinca', activities: ['Old Goa heritage walk', 'Coastal food tasting', 'Beach sunrise walk'], languages: ['Konkani', 'English', 'Hindi'] },
  hampi: { area: 'Hampi Bazaar and Kamalapur', type: 'heritage', specialty: 'North Karnataka meals, jolada rotti, and banana lassi', activities: ['Vijayanagara heritage walk', 'Tungabhadra coracle outing', 'Local craft workshop'], languages: ['Kannada', 'English', 'Hindi'] },
  coorg: { area: 'Madikeri and coffee country', type: 'nature', specialty: 'Kodava curry, akki rotti, and estate coffee', activities: ['Coffee estate walk', 'Waterfall nature outing', 'Kodava cooking session'], languages: ['Kodava', 'Kannada', 'English'] },
  mysore: { area: 'Mysore Palace and Devaraja Market', type: 'heritage', specialty: 'Mysore masala dosa and Mysore pak', activities: ['Palace heritage walk', 'Market food walk', 'Chamundi nature visit'], languages: ['Kannada', 'English', 'Hindi'] },
  bengaluru: { area: 'Central Bengaluru', type: 'city', specialty: 'Masala dosa, filter coffee, and local meals', activities: ['Market food walk', 'City heritage tour', 'Garden nature walk'], languages: ['Kannada', 'English', 'Hindi'] },
  bangalore: { area: 'Central Bengaluru', type: 'city', specialty: 'Masala dosa, filter coffee, and local meals', activities: ['Market food walk', 'City heritage tour', 'Garden nature walk'], languages: ['Kannada', 'English', 'Hindi'] },
  kerala: { area: 'Kochi and the Kerala coast', type: 'coastal', specialty: 'Appam, Kerala meals, and seasonal seafood', activities: ['Backwater nature outing', 'Spice and food walk', 'Coastal culture visit'], languages: ['Malayalam', 'English', 'Hindi'] }
};

const demoImages = {
  hotel: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=800&q=80',
  experience: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80',
  food: 'https://images.unsplash.com/photo-1515003197210-e0cd7184f8b5?auto=format&fit=crop&w=800&q=80',
  guide: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80'
};

export const getDestinationListingFallback = (destination = '') => {
  const name = String(destination || '').trim();
  const key = normalizeListingDestination(name);
  if (key === 'mangaluru') return mangaluruListings;

  const profile = fallbackProfiles[key] || {
    area: `Central ${name || 'your destination'}`,
    type: 'local',
    specialty: `Regional food and local specialties in ${name || 'your destination'}`,
    activities: ['Local heritage walk', 'Regional food tasting', 'Nature and neighborhood visit'],
    languages: ['English', 'Hindi']
  };
  const city = name || 'Mangaluru';
  const id = key || 'mangaluru';

  return {
    hotels: Array.from({ length: 6 }, (_, index) => ({
      id: `demo-${id}-hotel-${index + 1}`, name: [`${city} Heritage Stay`, `${city} Central Hotel`, `${city} Garden Residency`, `${city} Local Homestay`, `${city} Market View Inn`, `${city} Comfort Suites`][index],
      area: profile.area, destinationId: id, destinationName: city, type: ['Boutique Hotel', 'Hotel', 'Guesthouse', 'Homestay', 'City Hotel', 'Family Stay'][index],
      image: demoImages.hotel, pricePerNight: [1800, 2300, 2800, 3200, 3900, 4600][index], rating: [4.2, 4.4, 4.3, 4.6, 4.1, 4.5][index], reviewsCount: [36, 52, 41, 29, 64, 45][index],
      amenities: ['WiFi', 'AC', 'Breakfast', 'Parking'], distanceFromAttractions: `Near ${profile.area}`, cancellationPolicy: 'Demo listing · confirm details with property', roomsAvailable: index + 1,
      availability: 'Demo availability · confirm with property', verified: false, description: `Demo recommendation in ${profile.area} for travelers exploring ${city}.`
    })),
    experiences: Array.from({ length: 6 }, (_, index) => ({
      id: `demo-${id}-experience-${index + 1}`, title: profile.activities[index % profile.activities.length], destinationId: id,
      category: ['Culture', 'Food', 'Nature', 'Adventure', 'Fishing', 'Handicrafts'][index], host: `Local ${city} host · Demo listing`, hostVerified: false,
      price: [450, 600, 750, 900, 550, 700][index], duration: ['2 Hours', '2.5 Hours', '3 Hours', '2 Hours', '2.5 Hours', '2 Hours'][index],
      languages: profile.languages, rating: [4.6, 4.8, 4.5, 4.7, 4.4, 4.6][index], reviewsCount: [21, 32, 18, 27, 15, 20][index], image: demoImages.experience,
      description: `A demo ${profile.type} experience in ${city}, hosted around ${profile.area}.`, impactNote: 'Demo listing · confirm details locally before booking.', location: profile.area, availableSlots: 4 + index
    })),
    foods: Array.from({ length: 8 }, (_, index) => ({
      id: `demo-${id}-food-${index + 1}`, dishName: [`${city} regional meal`, profile.specialty, 'Local breakfast favorites', 'Seasonal vegetarian plate', 'Coastal or market lunch', 'Neighborhood snacks', 'Regional curry and rice', 'Local dessert'][index],
      restaurantName: `${city} Local Kitchen ${index + 1}`, destination: city, area: profile.area, cuisine: profile.type === 'coastal' ? 'Regional · Coastal' : 'Regional · Local cuisine',
      dietary: index % 2 === 0 ? 'Pure Veg' : 'Non-Veg', iconicRestaurant: `${city} Local Kitchen ${index + 1} · Demo listing`, priceRange: '₹120–₹450', hygieneRating: 'Local listing · Demo recommendation',
      description: `A demo food recommendation featuring ${profile.specialty}.`, mustTryBadge: 'Local recommendation', rating: 4.2 + (index % 5) / 10, reviewsCount: 20 + index * 7, image: demoImages.food,
      openingHours: 'Hours vary; confirm with the restaurant'
    })),
    guides: Array.from({ length: 6 }, (_, index) => ({
      id: `demo-${id}-guide-${index + 1}`, name: [`Asha Rao`, `Naveen Kumar`, `Meera Shetty`, `Arun Das`, `Kavya Nair`, `Rohan Pai`][index], destinationId: id, destinationName: city,
      photo: demoImages.guide, languages: index % 2 ? ['English', 'Hindi'] : profile.languages, expertise: [['Heritage', 'Local history'], ['Food', 'Markets'], ['Nature', 'Photography'], ['Culture', 'Architecture'], ['Beaches', 'Coastal walks'], ['Local history', 'Food']][index],
      dailyFee: 1100 + index * 150, experienceYears: 3 + index, rating: 4.3 + (index % 5) / 10, reviewsCount: 18 + index * 9,
      verifiedBadge: 'Demo profile · Verification not provided', verified: false, bio: `Demo local guide profile for ${city}, with interests in ${profile.type} visits and neighborhood stories.`, phone: 'Contact via TripEase demo'
    }))
  };
};
