export const indianDestinations = [
  { id: 'bengaluru', name: 'Bengaluru', state: 'Karnataka', country: 'India', latitude: 12.9716, longitude: 77.5946, description: 'The Garden City blends culture, nightlife, tech parks, and easy access to the Western Ghats.', attractions: ['UB City', 'Lalbagh Botanical Garden', 'Bangalore Palace', 'Nandi Hills'], categories: ['City', 'Food', 'Culture'], estimatedBudget: 2600, bestTime: 'October to March', localFood: 'Mysore masala dosa, filter coffee, biryani', activities: ['Food crawl', 'Garden walk', 'Night market stroll'] },
  { id: 'mysuru', name: 'Mysuru', state: 'Karnataka', country: 'India', latitude: 12.2958, longitude: 76.6394, description: 'A heritage city known for palace grandeur, gardens, and calm walks through royal avenues.', attractions: ['Mysore Palace', 'Chamundi Hill', 'St. Philomena Church', 'Brindavan Gardens'], categories: ['Heritage', 'Culture'], estimatedBudget: 2200, bestTime: 'October to February', localFood: 'Mysore pak, dosas, traditional meals', activities: ['Palace tour', 'City drive', 'Cultural heritage walk'] },
  { id: 'coorg', name: 'Coorg', state: 'Karnataka', country: 'India', latitude: 12.4244, longitude: 75.7382, description: 'Misty hills, coffee estates, waterfalls, and cool weather make Coorg a favorite hill escape.', attractions: ['Abbey Falls', 'Dubare Elephant Camp', 'Raja Seat', 'Coffee plantations'], categories: ['Mountains', 'Adventure'], estimatedBudget: 3200, bestTime: 'September to May', localFood: 'Pandi curry, akki rotti, coffee', activities: ['Coffee plantation tour', 'Waterfall trek', 'Nature drive'] },
  { id: 'hampi', name: 'Hampi', state: 'Karnataka', country: 'India', latitude: 15.335, longitude: 76.4600, description: 'A UNESCO heritage landscape of granite boulders, temples, and sunset viewpoints.', attractions: ['Virupaksha Temple', 'Vijaya Vittala Temple', 'Matanga Hill', 'Hampi Bazaar'], categories: ['Heritage', 'Adventure'], estimatedBudget: 2500, bestTime: 'October to February', localFood: 'Local thali, fresh fruit, Karnataka snacks', activities: ['Temple tour', 'Sunset viewing', 'Bike ride'] },
  { id: 'gokarna', name: 'Gokarna', state: 'Karnataka', country: 'India', latitude: 14.5473, longitude: 74.3189, description: 'A laid-back beach town known for cliffside views, temple culture, and easy-going beaches.', attractions: ['Om Beach', 'Mahabaleshwar Temple', 'Kudle Beach', 'Paradise Beach'], categories: ['Beaches', 'Adventure'], estimatedBudget: 3000, bestTime: 'October to March', localFood: 'Seafood thali, roasted corn, coconut-based dishes', activities: ['Beach hopping', 'Trekking', 'Sunset yoga'] },
  { id: 'udupi', name: 'Udupi', state: 'Karnataka', country: 'India', latitude: 13.3409, longitude: 74.7421, description: 'A coastal temple town famed for its heritage, vegetarian cuisine, and clean beaches.', attractions: ['Sri Krishna Temple', 'Malpe Beach', 'St. Marys Island', 'Kaup Beach'], categories: ['Temples', 'Beaches', 'Food'], estimatedBudget: 2300, bestTime: 'October to March', localFood: 'Udupi dosa, neer dosa, rasam', activities: ['Temple visit', 'Beach walk', 'Local food trail'] },
  { id: 'mangaluru', name: 'Mangaluru', state: 'Karnataka', country: 'India', latitude: 12.9141, longitude: 74.8560, description: 'A busy port city with beaches, old markets, and a strong food and fish culture.', attractions: ['Panambur Beach', 'St. Aloysius Chapel', 'Tannirbhavi Beach', 'Mangalore Market'], categories: ['Beaches', 'Food'], estimatedBudget: 2400, bestTime: 'October to February', localFood: 'Ghee roast, Mangalorean fish curry', activities: ['Beach outing', 'Market walk', 'Seafood tasting'] },
  { id: 'manali', name: 'Manali', state: 'Himachal Pradesh', country: 'India', latitude: 32.2432, longitude: 77.1892, description: 'Snowy peaks, pine valleys, trekking routes, and mountain cafés define this Himalayan favorite.', attractions: ['Solang Valley', 'Rohtang Pass', 'Hadimba Temple', 'Old Manali'], categories: ['Mountains', 'Adventure'], estimatedBudget: 4500, bestTime: 'March to June and September to November', localFood: 'Siddu, momos, local thukpa', activities: ['Trekking', 'River rafting', 'Snow activities'] },
  { id: 'shimla', name: 'Shimla', state: 'Himachal Pradesh', country: 'India', latitude: 31.1048, longitude: 77.1734, description: 'A scenic hill station famous for colonial charm, viewpoints, and snow-laced roads.', attractions: ['The Ridge', 'Kufri', 'Jakhoo Temple', 'Mall Road'], categories: ['Mountains', 'Heritage'], estimatedBudget: 3800, bestTime: 'March to June', localFood: 'Chana madra, Himachali dham', activities: ['Hill drive', 'Toy train ride', 'Market walk'] },
  { id: 'dharamshala', name: 'Dharamshala', state: 'Himachal Pradesh', country: 'India', latitude: 32.2191, longitude: 76.3234, description: 'A spiritual and scenic town with mountain views, monasteries, and Tibetan culture.', attractions: ['McLeod Ganj', 'Namgyal Monastery', 'Triund', 'Bhagsu Falls'], categories: ['Mountains', 'Culture'], estimatedBudget: 3500, bestTime: 'March to June and September to November', localFood: 'Thukpa, momos, Tibetan breads', activities: ['Monastery visit', 'Trekking', 'Tea house stroll'] },
  { id: 'rishikesh', name: 'Rishikesh', state: 'Uttarakhand', country: 'India', latitude: 30.0869, longitude: 78.2676, description: 'A riverside pilgrimage town known for yoga, Ghats, and adventure sports on the Ganga.', attractions: ['Laxman Jhula', 'Triveni Ghat', 'Neelkanth Mahadev', 'Rajaji National Park'], categories: ['Adventure', 'Spiritual'], estimatedBudget: 2800, bestTime: 'September to November and February to April', localFood: 'Aloo puri, kachori, local sweets', activities: ['River rafting', 'Yoga', 'Ganga aarti'] },
  { id: 'nainital', name: 'Nainital', state: 'Uttarakhand', country: 'India', latitude: 29.3803, longitude: 79.4636, description: 'A lake town surrounded by mountains, known for boating, viewpoints, and hill-town charm.', attractions: ['Naini Lake', 'Snow View Point', 'Mall Road', 'Bhimtal'], categories: ['Mountains', 'Nature'], estimatedBudget: 3200, bestTime: 'March to June and September to November', localFood: 'Aloo tikki, Tibetan momos', activities: ['Boating', 'Lake walk', 'Sunset viewing'] },
  { id: 'mussoorie', name: 'Mussoorie', state: 'Uttarakhand', country: 'India', latitude: 30.4591, longitude: 78.0641, description: 'A hill station with misty roads, scenic viewpoints, and easy access to the Doon valley.', attractions: ['Gun Hill', 'Kempty Falls', 'Camel Back Road', 'Mall Road'], categories: ['Mountains', 'Nature'], estimatedBudget: 3600, bestTime: 'March to June', localFood: 'Maggi, local snacks, Punjabi meals', activities: ['Viewpoint drive', 'Nature walk', 'Market stroll'] },
  { id: 'jaipur', name: 'Jaipur', state: 'Rajasthan', country: 'India', latitude: 26.9124, longitude: 75.7873, description: 'India’s Pink City offers palaces, markets, and royal heritage set against desert skies.', attractions: ['Hawa Mahal', 'Amber Fort', 'City Palace', 'Jal Mahal'], categories: ['Heritage', 'Culture'], estimatedBudget: 3000, bestTime: 'October to March', localFood: 'Dal bati churma, ghewar', activities: ['Fort visit', 'Bazaar shopping', 'Heritage walk'] },
  { id: 'udaipur', name: 'Udaipur', state: 'Rajasthan', country: 'India', latitude: 24.5854, longitude: 73.7125, description: 'City of lakes, royal palaces, and romantic sunsets beside the Aravalli hills.', attractions: ['Lake Pichola', 'City Palace', 'Jag Mandir', 'Saheliyon ki Bari'], categories: ['Heritage', 'Lakes'], estimatedBudget: 3500, bestTime: 'October to March', localFood: 'Laal maas, kachori, kulfi', activities: ['Boat ride', 'Palace tour', 'Sunset cruise'] },
  { id: 'jodhpur', name: 'Jodhpur', state: 'Rajasthan', country: 'India', latitude: 26.2389, longitude: 73.0243, description: 'The Blue City is defined by forts, sandstone architecture, and lively bazaars.', attractions: ['Mehrangarh Fort', 'Umaid Bhawan', 'Clock Tower', 'Ghanta Ghar'], categories: ['Heritage', 'City'], estimatedBudget: 2800, bestTime: 'October to March', localFood: 'Makhaniya lassi, mirchi vada', activities: ['Fort tour', 'Market visit', 'Rooftop dining'] },
  { id: 'jaisalmer', name: 'Jaisalmer', state: 'Rajasthan', country: 'India', latitude: 26.9157, longitude: 70.9083, description: 'Golden dunes, desert camps, and historic forts define this iconic Rajasthan experience.', attractions: ['Jaisalmer Fort', 'Sam Sand Dunes', 'Patwon ki Haveli', 'Desert National Park'], categories: ['Desert', 'Heritage'], estimatedBudget: 4200, bestTime: 'October to March', localFood: 'Ker sangri, bajra roti, dal', activities: ['Desert safari', 'Night camp', 'Fort walk'] },
  { id: 'pushkar', name: 'Pushkar', state: 'Rajasthan', country: 'India', latitude: 26.4900, longitude: 74.5500, description: 'A spiritual town around the sacred Pushkar Lake and the famous Brahma temple.', attractions: ['Pushkar Lake', 'Brahma Temple', 'Savitri Temple', 'Camel Fair grounds'], categories: ['Spiritual', 'Heritage'], estimatedBudget: 2600, bestTime: 'October to March', localFood: 'Pahadi dishes, sweets, local snacks', activities: ['Lake walk', 'Temple visit', 'Camel ride'] },
  { id: 'goa', name: 'Goa', state: 'Goa', country: 'India', latitude: 15.2993, longitude: 74.1240, description: 'A beach destination with Portuguese heritage, nightlife, and easy coastal routes.', attractions: ['Baga Beach', 'Old Goa', 'Fort Aguada', 'Palolem Beach'], categories: ['Beaches', 'Food'], estimatedBudget: 4000, bestTime: 'November to February', localFood: 'Goan fish curry, vindaloo, bebinca', activities: ['Beach hopping', 'Food trail', 'Sunset cruise'] },
  { id: 'new-delhi', name: 'New Delhi', state: 'Delhi', country: 'India', latitude: 28.6139, longitude: 77.2090, description: 'A bustling capital mixing Mughal heritage, markets, and strong food culture.', attractions: ['India Gate', 'Qutub Minar', 'Red Fort', 'Connaught Place'], categories: ['Heritage', 'City'], estimatedBudget: 3000, bestTime: 'October to March', localFood: 'Chaat, kebabs, butter chicken', activities: ['City exploration', 'Market walk', 'Monument tour'] },
  { id: 'agra', name: 'Agra', state: 'Uttar Pradesh', country: 'India', latitude: 27.1767, longitude: 78.0081, description: 'Home to the Taj Mahal and a collection of Mughal heritage sites and local bazaars.', attractions: ['Taj Mahal', 'Agra Fort', 'Mehtab Bagh', 'Fatehpur Sikri'], categories: ['Heritage', 'Culture'], estimatedBudget: 2600, bestTime: 'October to March', localFood: 'Petha, tandoori dishes, Mughlai food', activities: ['Monument tour', 'Sunrise visit', 'Bazaar walk'] },
  { id: 'varanasi', name: 'Varanasi', state: 'Uttar Pradesh', country: 'India', latitude: 25.3176, longitude: 82.9739, description: 'A spiritual city with Ghats, rituals, and a layered sense of living heritage.', attractions: ['Dashashwamedh Ghat', 'Kashi Vishwanath', 'Assi Ghat', 'Sarnath'], categories: ['Spiritual', 'Culture'], estimatedBudget: 2200, bestTime: 'October to March', localFood: 'Banarasi paan, kachori, sweets', activities: ['Ghat walk', 'Aarti experience', 'Temple visit'] },
  { id: 'lucknow', name: 'Lucknow', state: 'Uttar Pradesh', country: 'India', latitude: 26.8467, longitude: 80.9462, description: 'A refined city known for Nishat, chikan embroidery, and heritage architecture.', attractions: ['Bara Imambara', 'Rumi Darwaza', 'Hazratganj', 'Chota Imambara'], categories: ['Heritage', 'Food'], estimatedBudget: 2500, bestTime: 'October to March', localFood: 'Awadhi biryani, kebabs, sheermal', activities: ['Heritage walk', 'Market shopping', 'Food trail'] },
  { id: 'kolkata', name: 'Kolkata', state: 'West Bengal', country: 'India', latitude: 22.5726, longitude: 88.3639, description: 'A creative cultural capital with colonial architecture, art, and beloved street food.', attractions: ['Victoria Memorial', 'Howrah Bridge', 'Dakshineswar Temple', 'Park Street'], categories: ['Culture', 'Food'], estimatedBudget: 2800, bestTime: 'October to March', localFood: 'Kathi rolls, phuchka, mishti doi', activities: ['Food trail', 'Cultural tour', 'Riverfront walk'] },
  { id: 'darjeeling', name: 'Darjeeling', state: 'West Bengal', country: 'India', latitude: 27.0360, longitude: 88.2627, description: 'A tea-growing Himalayan hill town known for scenic views and colonial charm.', attractions: ['Tiger Hill', 'Batasia Loop', 'Tea gardens', 'Mall Road'], categories: ['Mountains', 'Tea'], estimatedBudget: 3400, bestTime: 'March to June and September to November', localFood: 'Tea, momos, local snacks', activities: ['Tea garden tour', 'Sunrise view', 'Hill walk'] },
  { id: 'chennai', name: 'Chennai', state: 'Tamil Nadu', country: 'India', latitude: 13.0827, longitude: 80.2707, description: 'A coastal metropolis known for temples, food culture, and breezy beaches.', attractions: ['Marina Beach', 'Kapaleeshwarar Temple', 'Fort St. George', 'Mylapore'], categories: ['Beaches', 'Culture'], estimatedBudget: 2600, bestTime: 'November to February', localFood: 'Idli, filter coffee, dosa, seafood', activities: ['Beach walk', 'Temple visit', 'Night food crawl'] },
  { id: 'ooty', name: 'Ooty', state: 'Tamil Nadu', country: 'India', latitude: 11.4064, longitude: 76.6932, description: 'A cool highland retreat with tea gardens, trails, and quiet lakes.', attractions: ['Ooty Lake', 'Doddabetta Peak', 'Botanical Gardens', 'Tea factories'], categories: ['Mountains', 'Nature'], estimatedBudget: 3200, bestTime: 'April to June and September to October', localFood: 'Tea, local snacks, south Indian meals', activities: ['Lake boating', 'Tea estate tour', 'Hill viewpoints'] },
  { id: 'kodaikanal', name: 'Kodaikanal', state: 'Tamil Nadu', country: 'India', latitude: 10.2381, longitude: 77.4892, description: 'A misty plateau with lakes, pine forests, and cool mountain air.', attractions: ['Kodaikanal Lake', 'Coaker Walk', 'Bryant Park', 'Pillar Rocks'], categories: ['Mountains', 'Nature'], estimatedBudget: 3300, bestTime: 'April to June and September to October', localFood: 'South Indian breakfast, homemade chocolates', activities: ['Lake walk', 'Forest trails', 'Nature photo stops'] },
  { id: 'madurai', name: 'Madurai', state: 'Tamil Nadu', country: 'India', latitude: 9.9252, longitude: 78.1198, description: 'A historic temple city known for old streets, architecture, and vibrant cultural energy.', attractions: ['Meenakshi Temple', 'Thirumalai Nayakar Mahal', 'Gandhi Memorial Museum', 'Azhagar Kovil'], categories: ['Heritage', 'Culture'], estimatedBudget: 2200, bestTime: 'October to March', localFood: 'Jigarthanda, parotta, local snacks', activities: ['Temple exploration', 'Street food tasting', 'Market walk'] },
  { id: 'coimbatore', name: 'Coimbatore', state: 'Tamil Nadu', country: 'India', latitude: 11.0168, longitude: 76.9558, description: 'A fast-growing city near the Western Ghats with industry, food, and nearby hills.', attractions: ['Marudhamalai Temple', 'Siruvani Falls', 'Vellingiri Hills', 'Anamalai'], categories: ['City', 'Adventure'], estimatedBudget: 2400, bestTime: 'September to February', localFood: 'Kongu cuisine, filter coffee, biryani', activities: ['Hill drive', 'Temple visit', 'Food exploration'] },
  { id: 'rameswaram', name: 'Rameswaram', state: 'Tamil Nadu', country: 'India', latitude: 9.2876, longitude: 79.3129, description: 'A sacred island town known for shorelines, temples, and strong spiritual traditions.', attractions: ['Ramanathaswamy Temple', 'Dhanushkodi', 'Pamban Bridge', 'Agni Theertham'], categories: ['Spiritual', 'Beaches'], estimatedBudget: 2400, bestTime: 'October to April', localFood: 'Seafood, rice dishes, local snacks', activities: ['Temple visit', 'Beach walk', 'Coastal drive'] },
  { id: 'mumbai', name: 'Mumbai', state: 'Maharashtra', country: 'India', latitude: 19.0760, longitude: 72.8777, description: 'A mega city with iconic landmarks, coastal roads, and one of India’s richest food scenes.', attractions: ['Gateway of India', 'Marine Drive', 'Elephanta Caves', 'Colaba Causeway'], categories: ['City', 'Food'], estimatedBudget: 3600, bestTime: 'November to February', localFood: 'Vada pav, pav bhaji, Maharashtrian thali', activities: ['Coastal walk', 'Street food hunt', 'Monsoon sightseeing'] },
  { id: 'pune', name: 'Pune', state: 'Maharashtra', country: 'India', latitude: 18.5204, longitude: 73.8567, description: 'A lively city with culture, heritage, and easy access to hill stations and forts.', attractions: ['Shaniwar Wada', 'Aga Khan Palace', 'Sinhagad Fort', 'Lonavala'], categories: ['City', 'Heritage'], estimatedBudget: 2600, bestTime: 'October to February', localFood: 'Misal pav, poha, local sweets', activities: ['Fort visit', 'Night outing', 'Food walk'] },
  { id: 'nashik', name: 'Nashik', state: 'Maharashtra', country: 'India', latitude: 20.0110, longitude: 73.7900, description: 'A holy city and vineyard region with temples, trails, and grape-growing landscapes.', attractions: ['Trimbakeshwar', 'Sula Vineyards', 'Pandavleni Caves', 'Godavari River'], categories: ['Spiritual', 'Wine'], estimatedBudget: 2800, bestTime: 'October to March', localFood: 'Local thali, fruit, wines', activities: ['Vineyard tour', 'Temple visit', 'River walk'] },
  { id: 'mahabaleshwar', name: 'Mahabaleshwar', state: 'Maharashtra', country: 'India', latitude: 17.9286, longitude: 73.6533, description: 'A cool hill retreat offering viewpoints, strawberries, and hill roads full of greenery.', attractions: ['Wilson Point', 'Mapro Garden', 'Lingmala Falls', 'Arthur Seat'], categories: ['Mountains', 'Food'], estimatedBudget: 3200, bestTime: 'October to June', localFood: 'Strawberry cream, local snacks', activities: ['Hill driving', 'Picnic', 'Viewpoints'] },
  { id: 'lonavala', name: 'Lonavala', state: 'Maharashtra', country: 'India', latitude: 18.7553, longitude: 73.4076, description: 'A popular monsoon getaway with waterfalls, rolling hills, and easy day-trip access from Mumbai.', attractions: ['Khandala', 'Bhushi Dam', 'Lonavala Lake', 'Tungarli Lake'], categories: ['Mountains', 'Adventure'], estimatedBudget: 2600, bestTime: 'June to September', localFood: 'Chikki, local snacks, Indian meals', activities: ['Waterfall visit', 'Monsoon drive', 'Tea break'] },
  { id: 'kochi', name: 'Kochi', state: 'Kerala', country: 'India', latitude: 9.9312, longitude: 76.2673, description: 'A historic port city with Chinese fishing nets, backwaters, and strong multicultural flavors.', attractions: ['Fort Kochi', 'Jew Town', 'Chinese Fishing Nets', 'Mattancherry Palace'], categories: ['Heritage', 'Beaches'], estimatedBudget: 3200, bestTime: 'October to February', localFood: 'Appam, fish curry, Kerala sadya', activities: ['Heritage walk', 'Backwater cruise', 'Food trail'] },
  { id: 'munnar', name: 'Munnar', state: 'Kerala', country: 'India', latitude: 10.0889, longitude: 77.0595, description: 'A lush green hill station dotting tea gardens and misty gaps in the Western Ghats.', attractions: ['Eravikulam National Park', 'Tea Gardens', 'Mattupetty Dam', 'Top Station'], categories: ['Mountains', 'Nature'], estimatedBudget: 3500, bestTime: 'September to May', localFood: 'Kerala meals, tea, banana chips', activities: ['Tea garden tour', 'Trek', 'Sunrise drive'] },
  { id: 'alleppey', name: 'Alleppey', state: 'Kerala', country: 'India', latitude: 9.4981, longitude: 76.3388, description: 'Famous for houseboat cruises, lagoons, and relaxed backwater experiences.', attractions: ['Backwaters', 'Alleppey Beach', 'Houseboat route', 'Pathiramanal Island'], categories: ['Backwaters', 'Nature'], estimatedBudget: 2800, bestTime: 'September to March', localFood: 'Kerala fish curry, toddy shop meals', activities: ['Houseboat stay', 'Canal ride', 'Sunset boat trip'] },
  { id: 'wayanad', name: 'Wayanad', state: 'Kerala', country: 'India', latitude: 11.6854, longitude: 76.1320, description: 'A green forested district with waterfalls, wildlife, and rustic trekking trails.', attractions: ['Soochippara Falls', 'Edakkal Caves', 'Pookode Lake', 'Banasura Sagar'], categories: ['Wildlife', 'Nature'], estimatedBudget: 3000, bestTime: 'October to May', localFood: 'Malabar biryani, tea', activities: ['Wildlife safari', 'Waterfall trek', 'Forest drive'] },
  { id: 'thiruvananthapuram', name: 'Thiruvananthapuram', state: 'Kerala', country: 'India', latitude: 8.5241, longitude: 76.9366, description: 'A coastal city with beaches, temples, and a quieter, more heritage-rich coastal feel.', attractions: ['Padmanabhaswamy Temple', 'Kovalam Beach', 'Napier Museum', 'Sree Chitra Art Gallery'], categories: ['Culture', 'Beaches'], estimatedBudget: 2800, bestTime: 'October to February', localFood: 'Kerala sadya, seafood, banana chips', activities: ['Temple visit', 'Beach time', 'Museum walk'] },
  { id: 'kozhikode', name: 'Kozhikode', state: 'Kerala', country: 'India', latitude: 11.2588, longitude: 75.7804, description: 'Known for historic spice routes, beach views, and excellent Malabar cuisine.', attractions: ['Kozhikode Beach', 'Mananchira Square', 'Beypore', 'Azhakodi'], categories: ['Food', 'Culture'], estimatedBudget: 2400, bestTime: 'October to February', localFood: 'Malabar biryani, seafood, pathiri', activities: ['Food trail', 'Beach walk', 'Old city exploration'] },
  { id: 'panaji', name: 'Panaji', state: 'Goa', country: 'India', latitude: 15.4909, longitude: 73.8278, description: 'Goa’s capital mixes Portuguese architecture with a small, walkable city center.', attractions: ['Fontainhas', 'Church of Our Lady of the Immaculate Conception', 'Miramar Beach', 'Campal'], categories: ['Culture', 'Beaches'], estimatedBudget: 3200, bestTime: 'November to February', localFood: 'Chicken xacuti, pork vindaloo, bebinca', activities: ['Heritage walk', 'Sunset beach', 'Cafe hopping'] },
  { id: 'calangute', name: 'Calangute', state: 'Goa', country: 'India', latitude: 15.5430, longitude: 73.7554, description: 'A lively beach belt known for sands, nightlife, and surfing-friendly coasts.', attractions: ['Calangute Beach', 'Baga Beach', 'Candolim Beach', 'Nightlife strip'], categories: ['Beaches', 'Adventure'], estimatedBudget: 3500, bestTime: 'November to February', localFood: 'Seafood, vindaloo, local drinks', activities: ['Beach vacation', 'Night life', 'Water sports'] }
];

export const defaultDestination = indianDestinations.find(item => item.name === 'Bengaluru') || indianDestinations[0];

export const normalizeDestinationValue = (value) => String(value || '').toLowerCase().replace(/[^a-z0-9]/g, '');

export const findDestinationByQuery = (query = '') => {
  const trimmed = String(query || '').trim();
  if (!trimmed) return [...indianDestinations];

  const lower = trimmed.toLowerCase();
  return indianDestinations.filter((item) => {
    const haystack = [
      item.name,
      item.state,
      item.country,
      item.description,
      ...(item.attractions || []),
      ...(item.categories || []),
      ...(item.activities || [])
    ].join(' ').toLowerCase();
    return haystack.includes(lower) || normalizeDestinationValue(item.name).includes(normalizeDestinationValue(lower));
  });
};

export const buildDestinationSearchResults = (query = '') => {
  const matches = findDestinationByQuery(query);
  return matches.slice(0, 12).map((item) => ({
    id: item.id,
    name: item.name,
    state: item.state,
    country: item.country,
    latitude: item.latitude,
    longitude: item.longitude,
    description: item.description,
    categories: item.categories,
    attractions: item.attractions,
    bestTime: item.bestTime,
    estimatedBudget: item.estimatedBudget,
    localFood: item.localFood,
    activities: item.activities
  }));
};
